### ISSUE TITLE
domc vs stage0

### ISSUE THREAD

**Issue by trusktr** [Freak613/domc#4]
Why two libs? What are their differences? Were you experimenting with two different ways of doing things? It would be interesting to know. :)

**Comment by Freak613** [comment]
domc was the first as result of researching fastest way to create DOM elements.

However, when I tried to apply it to different cases I found that it has limits, in both API and performance, and scales not well having a lot of components. domc is opinionated library in how things can be done and it was limiting me.

Then I exported good findings from domc as standalone library of small reusable functions and found that playing with that was much more fun, allowing to build fine tuned components and have clear understanding what the code does, basically not having any 'magic' inside. And I liked it and released as stage0, that means "helpers to work on VanillaJS level".

**Comment by ryansolid** [comment]
If I may,

I think of Stage0 as the new jQuery(if you picture how jQuery was received in 2007 and not how people think about it now). It has everything you need to make modern performant data driven templated js rendered applications. It is based off such a simple concept of tagging the things you care about in the DOM. It's like reverse jQuery selectors, as you mark the markup instead of writing matching patterns into your code. The helper functions are simple to use and have all the techniques the most performant libraries use for reconciling lists. This little library exposes the hidden tricks and the complicated pieces of other libraries in a way that you can just make a simple function calls. I know from hours and hours of benchmarking and researching tons of libraries in trying to write my own framework the key parts are right here for anyone to pick up and use.

That's my back of the box pitch. If that is what you are looking for in a library it doesn't get any purer.

**Comment by ryansolid** [comment]
Yeah no doubt. I actually think React actually was able to come in with the performance argument mostly through good marketing.  The whole Virtual DOM faster that the real DOM was like shooting fish in a barrel on the jQuery/Backbone I update with innerHTML side, but wasn't even definitive across the board. Databound libraries proceeded React by 3-4 years and were more performant in a number of benchmark tests. I mean round 1 of JS Frameworks Benchmark was only Jan 2016, and compare Angular 1 to React. And that is a good couple years after React showed up on the scene. Angular 1 dates back to 2009 and was already end of lifed. I could go on about how incorrect React's marketing was, but no one can argue it wasn't good marketing.

**Comment by trsh** [comment]
@Freak613 so what do I use for a new project? And what will be better supported?

**Comment by Freak613** [comment]
Actually, you should pick that one that is better fit your usecase.

I recommend stage0 as it's much simpler and more flexible, while domc missing some features right now and you need to write new directives for that using directives API.

stage0 requires knowledge of native DOM API, not everything but most commonly used.
This is some random DOM API cheatsheet for example:
https://gist.github.com/thegitfather/9c9f1a927cd57df14a59c268f118ce86

Building for performance is very hard task, this library trying to help with some tools for using with DOM API and doesn't provide performance in convenient React way.
These two libraries right now more of state of art of researching performance approaches in the web, you can use it for fun.
Though I have successful experience with building complex UIs using stage0, it still just an experiment.
